name: Checkout Workflow
run-name: Checkout Workflow v3
on: push
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - run: ls -al
      - uses: actions/checkout@v4
        with:
          repository: actions/checkout
          ref: v4.1.7
      - run: ls -al
      - run: head -n CHANGELOG.md
