name: Checkout Workflow
run-name: Checkout Workflow v2
on: push
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - run: ls -al
      - uses: actions/checkout@v4
      - run: ls -al
      - run: ls -al .github
      - run: ls -al .github/workflows
      - run: cat .github/workflows/github-action-checkout-01.yml
