name: Context testing
run-name: Run var test
on: push

jobs:
  display-variables:  
    runs-on: ubuntu-latest
    steps:
    - name: ${{ vars.HELLO_WORLD_STEP }}
      if: ${{ vars.HELLO_WORLD_ENABLED == 'true' }}
      uses: actions/hello-world-javascript-action@main
      with:
        who-to-greet: ${{ vars.GREET_NAME }}
