name: Greeting on variable day

on: push
env:
  DAY_OF_WEEK: Friday
jobs:
  greeting_job_v1:
    runs-on: ubuntu-latest
    env:
      Greeting: Welcome to
    steps:
      - name: "Say Welcome to GithubActions it's Friday"
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
        env:
          First_Name: GithubActions
