name: Checkout Workflow
run-name: Checkout Workflow v3
on: push
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - run: ls -al
      - uses: actions/checkout@v4.2.2
        with:
          repository: actions/checkout
          ref: v4.2.2
      - run: ls -al
      - run: head -n 10 CHANGELOG.md
      - run: ls -al .github/workflows
