name: Run CI
run-name: Run CI v2 (context)
on: push

jobs:
  normal_ci:
    runs-on: ubuntu-latest
    steps:
      - name: Run normal CI
        run: echo "Running normal CI"

  pull_request_ci:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull' }}
    steps:
      - name: Run PR CI
        run: echo "Running PR only CI"
